feat add progile page
rarimo/rarime-dashboard pull request #4
Opened 2023-11-22 15:42 UTC by WhiteNik16

2023-11-23 08:56 UTC, napalmpapalam requested changes

2023-11-23 08:56 UTC, napalmpapalam commented on index.html
> +  <link rel="preload" href="/branding/fonts/EuclidCirculiarB/Euclid-Circular-B-Bold.ttf" as="font" type="font/ttf" crossorigin="anonymous">
convert fonts to woff2 https://onlinefontconverter.com/

2023-11-23 08:56 UTC, napalmpapalam commented on src/enums/credential_name.enum.ts
> +}
all enums in the project has inconsistent case, some names LIKE_THIS some LikeThis, some fields with lowercase some with PascalCase, fix it plz, enum name and fields should be in PascalCase like in ts doc https://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/ProfilePage.tsx
> +
why components not in the components dir ? and why u import it via absolute path instead of reexport from index.ts?

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/ProfilePage.tsx
> +    const userCredentials = await getCredentials()
redundant variable

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/components/CredentialsTile/styles.scss
> +  :after {
do u have stylelint? no space after class selector and space after `:after {` selector

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/components/CredentialsTile/styles.scss
> +.credential-tile__footer-provider_icon{
same here

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/components/Sidebar/Sidebar.tsx
> +                  String(provider?.providerType) as keyof typeof ICON_NAMES
extract type to the `@/types` coz u use it few times

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/styles.scss
> +  padding: var(--app-primary-page-padding) var(--app-primary-page-padding) var(--app-primary-page-padding) calc(var(--app-sidebar-width) + var(--app-padding-left) + (var(--app-padding-right)));
move `calc(var(--app-sidebar-width) + var(--app-padding-left) + (var(--app-padding-right)))` to var and use there and in the navbar

2023-11-23 08:56 UTC, napalmpapalam commented on src/pages/ProfilePage/styles.scss
> +.profile-page__content-empty_description {
why `.profile-page__content-empty_description` and not `.profile-page__content-empty-description` ? there a lot of such cases recheck all plz

2023-11-23 09:26 UTC, WhiteNik16 commented on src/pages/ProfilePage/components/CredentialsTile/styles.scss
> +.credential-tile__footer-provider_icon{
fixed

2023-11-23 12:18 UTC, WhiteNik16 commented on src/pages/ProfilePage/styles.scss
> +.profile-page__content-empty_description {
fixed

2023-11-23 12:27 UTC, WhiteNik16 commented on src/pages/ProfilePage/styles.scss
> +  padding: var(--app-primary-page-padding) var(--app-primary-page-padding) var(--app-primary-page-padding) calc(var(--app-sidebar-width) + var(--app-padding-left) + (var(--app-padding-right)));
fixed

2023-11-23 12:38 UTC, WhiteNik16 commented on index.html
> +  <link rel="preload" href="/branding/fonts/EuclidCirculiarB/Euclid-Circular-B-Bold.ttf" as="font" type="font/ttf" crossorigin="anonymous">
fixed

2023-11-23 12:47 UTC, WhiteNik16 commented on src/pages/ProfilePage/components/CredentialsTile/styles.scss
> +  :after {
ашчув

2023-11-23 12:48 UTC, WhiteNik16 commented on src/pages/ProfilePage/components/CredentialsTile/styles.scss
> +.credential-tile__footer-provider_icon{
fixed

2023-11-23 12:52 UTC, WhiteNik16 commented on src/pages/ProfilePage/styles.scss
> +  padding: var(--app-primary-page-padding) var(--app-primary-page-padding) var(--app-primary-page-padding) calc(var(--app-sidebar-width) + var(--app-padding-left) + (var(--app-padding-right)));
fixed

2023-11-23 12:52 UTC, WhiteNik16 commented on src/pages/ProfilePage/styles.scss
> +.profile-page__content-empty_description {
fixed

2023-11-23 12:54 UTC, WhiteNik16 commented on src/pages/ProfilePage/ProfilePage.tsx
> +    const userCredentials = await getCredentials()
fixed

2023-11-23 23:18 UTC, WhiteNik16 commented on src/pages/ProfilePage/ProfilePage.tsx
> +
fixed

2023-11-23 23:22 UTC, WhiteNik16 commented on src/pages/ProfilePage/components/Sidebar/Sidebar.tsx
> +                  String(provider?.providerType) as keyof typeof ICON_NAMES
fixed

2023-11-24 08:35 UTC, napalmpapalam requested changes

2023-11-24 08:35 UTC, napalmpapalam commented on src/enums/icon-names.enum.ts
>    accountBalanceWallet = 'account-balance-wallet',
few properties still camelCase

2023-11-24 08:35 UTC, napalmpapalam commented on src/types/common.types.ts
> +  iconName?: IconNames // FIXME
what the FIXME is here?

2023-11-24 11:56 UTC, WhiteNik16 commented on src/enums/icon-names.enum.ts
>    accountBalanceWallet = 'account-balance-wallet',
fixed

2023-11-24 11:56 UTC, WhiteNik16 commented on src/enums/window-breakpoints.enum.ts
>    small = 600,
fixed

2023-11-24 11:56 UTC, WhiteNik16 commented on src/types/common.types.ts
> +  iconName?: IconNames // FIXME
fixed

2023-11-24 11:59 UTC, napalmpapalam approved these changes

2023-11-24 11:59 UTC, merged